spring.application.name: MovieLog

kinopoisk:
  baseUrl: https://kinopoiskapiunofficial.tech/api
  apiKey: your_api_key

spring:
  datasource:
    url: your_url
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true