spring.application.name: MovieLog

kinopoisk:
  baseUrl: https://kinopoiskapiunofficial.tech/api
  apiKey: ${KP_API_KEY}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties.hibernate.format_sql: true